### ISSUE TITLE
Login failure with authn-node

### ISSUE THREAD

**Issue by jeff-zucker** [inrupt/solid-client-authn-js#1285] opened 2021-04-19 17:54 UTC
### Impacted package

solid-client-authn-node and possibly generate-oidc-token

### Bug description

Can not login.

### To Reproduce
1.  Get a token with generate-oidc-token
2.  Run this script  (which worked fine previously):
```javascript
import { Session } from "@inrupt/solid-client-authn-node";                      
const {getCredentials} = require('../../getCredentials');                       
                                                                                
async function login() {                                                        
  const sess = new Session();                                                   
  const creds = await getCredentials('jeff-zucker@inrupt.com');                 
  await sess.login(creds);                                                      
  return session;                                                               
}                                                                               
                                                                                
(async ()=>{                                                                    
  let s = await login();                                                        
  console.log(s)                                                                
})()                                                                            
```                                                                                
 
### Expected result

console log of the session object

### Actual result
```
(node:192246) UnhandledPromiseRejectionWarning: Error: Invalid refresh credentials: OPError: invalid_grant (Invalid refresh_token)
    at refreshAccess (/home/jeff/Dropbox/Web/solid/solid-node-client/node_modules/@inrupt/solid-client-authn-node/dist/login/oidc/oidcHandlers/RefreshTokenOidcHandler.js:49:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RefreshTokenOidcHandler.handle (/home/jeff/Dropbox/Web/solid/solid-node-client/node_modules/@inrupt/solid-client-authn-node/dist/login/oidc/oidcHandlers/RefreshTokenOidcHandler.js:79:28)
    at async ClientAuthentication.login (/home/jeff/Dropbox/Web/solid/solid-node-client/node_modules/@inrupt/solid-client-authn-node/dist/ClientAuthentication.js:26:33)
    at async Session.login (/home/jeff/Dropbox/Web/solid/solid-node-client/node_modules/@inrupt/solid-client-authn-node/dist/Session.js:15:31)
    at async login (/home/jeff/Dropbox/Web/solid/solid-node-client/drafts/login-scan.js:7:3)
    at async /home/jeff/Dropbox/Web/solid/solid-node-client/drafts/login-scan.js:12:11
(node:192246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:192246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
```code
  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 167.12 MB / 11.61 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.72
    Firefox: 87.0
  npmPackages:
    @babel/cli: ^7.13.14 => 7.13.14 
    @babel/core: ^7.13.15 => 7.13.15 
    @babel/plugin-transform-modules-commonjs: ^7.13.8 => 7.13.8 
    @inrupt/generate-oidc-token: ^0.1.1 => 0.1.1 
    @inrupt/solid-client: ^1.6.1 => 1.6.1 
    @inrupt/solid-client-authn-node: ^1.7.4 => 1.7.4 
    @solid-rest/file: ^2.0.7 => 2.0.7 
    rdflib: ^2.2.0 => 2.2.0 
    solid-auth-fetcher: ^1.5.2 => 1.5.2 
    typescript: 4.2.4 => 4.2.4 
  npmGlobalPackages:
    esm: 3.2.25
    nativefier: 43.0.0
    nodemon: 2.0.6
    npm-check-updates: 11.4.1
    npm: 6.14.8
    shelljs: 0.8.4
    typedoc: 0.19.2
    typescript: 4.1.2
```

**Comment by nicolasmondada** [comment] 2021-04-20 10:13
Hi @jeff-zucker ,

Thanks for reporting this. We will be looking into this shortly and get back to you as soon as we can.

Cheers,
Nick.-

**Comment by NSeydoux** [comment] 2021-04-20 11:17
Hi @jeff-zucker ! This issue stems from an update in the behaviour of the ESS Identity Broker that was released recently. For security reasons, the refresh token is now rotated: each time the refresh token is used, a new refresh token is emitted, and the previous one is invalidated. So far, `@inrupt/solid-client-authn-node` has only handled this using the storage associated to the session (by default, an in memory storage). This means that when a new refresh token is received, it is saved in storage to be used on the next request.

This works fine, as long as the storage is persistent, which isn't the case with the default in-memory storage, which gets wiped when the script stops. One mitigation to the issue would be to ship a permanent storage with the library. For instance, if you look at https://github.com/inrupt/solid-client-authn-js/tree/main/packages/node/example/bootstrappedApp/src, an example filesystem storage is implemented.Initially, you'd need to call `authenticatedScript.ts` once with the refresh token obtained from `generate-oidc-token`, and then the latest token would alway be available in storage. 

However, depending on the context, using a custom storage may be inconvenient. That's why I'm currently working on https://github.com/inrupt/solid-client-authn-js/pull/1284, which would add a hook for a callback that gets called when a new refresh token is returned. This means that instead of using the session storage to manage refresh tokens, you may use whatever custom system that fits in your setup.

Moreover, there is a second, somewhat related issue that I'll fix as soon as possible too: the new ID broker revealed a small bug in `@inrupt/solid-client-authn-node` which technically made it non-OIDC compliant. The fix has been released as part of `1.7.4`, but `@inrupt/generate-oidc-token` has yet to be upgraded to the latest version. I'll update this issue as soon as it is done.

**Comment by NSeydoux** [comment] 2021-04-21 06:03
Hi @jeff-zucker . I just released `@inrupt/generate-oidc-token@0.1.2`, which is now compatible with the new ESS ID broker, and `@inrupt/solid-client-authn-node@1.8.0`, which includes a hook for a callback to help manage the refresh token. I updated https://github.com/inrupt/solid-client-authn-js/blob/a760a812d0e728efdcb7308ef608ba2d28194713/packages/node/example/bootstrappedApp/src/authenticatedScript.ts#L28 with an example on how to use this new feature, and I'm working right now on updating the docs.

Basically, if you provide an `onNewRefreshToken` callback, it will be invoked whenever the Identity Provider sends a new refresh token. When token rotation is implemented by the Identity Provider (which is regarded as a good practice), each time a refresh token is used, a new refresh token is provided. The `onNewRefreshToken` callback would then be invoked, so that you can run custom code to update a file, an environment variable, or whatever means you have to manage the refresh token.

In order to get back on track, you'll need to use `@inrupt/generate-oidc-token` once, to get a valid refresh token, and from then on to use either the storage or the `onNewRefreshToken` callback to keep track of the refresh token. I hope this helps resolving your issue.

**Comment by jeff-zucker** [comment] 2021-04-21 19:49
@zwifi and @nicolasmonada, thanks for your attention to this issue.  I upgraded everything ran getToken and tried the exact script you pointed to and could not login.  I will confess that I am pretty much at the end of my rope.  I have spent a lot of time trying to use out-of-browser access to ESS and, so far, nothing has remained working for more than a few weeks.  I totally understand that this is an issue of resources and priorities and I do trust that you and others at Inrupt are doing the best possible in this situation.  But, from a purely selfish viewpoint, I'd like to actually write some software rather than continually chase changes in something I have no control over.  So, at the moment, although I'll give it some more thought, I am planning on dropping support for ESS from my out-of-browser libraries. I very much appreciate the hard work you have put into this and your rapid response to issues and look forward to collaborating with you on other matters.

**Comment by jeff-zucker** [comment] 2021-08-04 22:34
Bump, please.  @NSeydoux.  I am now getting "invalid client credentials" on both NSS and ESS by running generate-oidc-token@0.1.2 and then trying to login with solid-client-authn-node@1.10.1.

**Comment by NSeydoux** [comment] 2021-08-06 16:09
Hi @jeff-zucker , thanks for following up ! The latest bug is due to the addition of a still undocumented feature that should help running scripts without having to bother with `generate-oidc-token` (at least on ESS). I'll let you know as soon as the documentation is out ! I'll also fix the bug you're currently facing and release the fix asap.

**Comment by NSeydoux** [comment] 2021-08-13 16:00
Sorry for the delay, I finally manage to release things. As soon as https://github.com/inrupt/generate-oidc-token/pull/147 is merged you should be good to go, and using `@inrupt/generate-oidc-token@main` should already resolve your issue.

**Comment by NSeydoux** [comment] 2021-08-20 17:25
Can you confirm that the problem is resolved, and if so close the issue ?

**Comment by jeff-zucker** [comment] 2021-08-20 17:33
Sorry, I am swamped trying to integrate Jackson's new auth into SolidOS and Data-Kitchen.  Will get back to node stuff as soon as Ic can.  I appreciate your work but unfortunately won't be able to make use of it immediately.  Will post here as soon as I have had a chance to test.  I did run generate-oidc-token on solidcommunity.net and it sent back what looked like a good token.  Haven't had time to download latest solid-client-authn-node and try to use the token though.

**Comment by NSeydoux** [comment] 2021-08-24 13:50
That's absolutely fine, no worries: my concern was that you'd still be blocked, if you're not that's great :)

**Closed** 2022-05-05 12:48 UTC
Labels: bug
