### ISSUE TITLE
Cannot import in a module with Skypack

### ISSUE THREAD

**Issue by matthieu-fesselier** [inrupt/solid-client-authn-js#991] opened 2021-01-26 13:53 UTC
### Search terms you've used
skypack, import, node-forge

### Impacted package

Which packages do you think might be impacted by the bug ?

- [X] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext

### Bug description
When I import the library in a JS module with [Skypack](https://www.skypack.dev/), I get a build error of `node-forge`:
```
[Package Error] "node-forge@v0.10.0" could not be built. (Imported by "node-jose").
``` 
This error can be seen here: https://cdn.skypack.dev/new/node-forge@v0.10.0/dist=es2020

### To Reproduce
1. Open the example here: https://plnkr.co/edit/RdZVkjafOpcE3Wrn?open=lib%2Fscript.js
2. Check the console logs

### Expected result
I expect the `Session` to be available without errors in console

### Actual result
The lib is not loaded at all

### Environment
```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 AMD Ryzen 3 3250U with Radeon Graphics
    Memory: 1.05 GB / 5.75 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
  npmPackages:
    @inrupt/solid-client: ^1.3.0 => 1.3.0 
    @inrupt/solid-client-authn-browser: ^1.4.2 => 1.4.2 
    @inrupt/vocab-common-rdf: ^0.7.2 => 0.7.2 
    babel-eslint: ^10.1.0 => 10.1.0 
    eslint: ^7.0.0 => 7.0.0 
    eslint-config-airbnb-base: ^14.1.0 => 14.1.0 
    eslint-plugin-import: ^2.20.2 => 2.20.2 
    live-server: ^1.2.1 => 1.2.1 
    oidc-client: ^1.10.1 => 1.10.1 

```

**Comment by NSeydoux** [comment] 2021-02-04 10:40
Hi @matthieu-fesselier , thanks for reporting this, and sorry for the delayed response ! 

We intend to switch to `jose@v3.x`, and doing so would no longer require us depending on `node-jose`, so I think that would solve your issue. However, switching to `jose@v3.x` means we no longer support NodeJS@10, so we'll only make the switch in April after official support for NodeJS10 is dropped. 

I think a possible cause for the issue is that `node-jose` requires some node builtins which must be polyfilled for the bundler to work (see our [webpack configuration](https://github.com/inrupt/solid-client-authn-js/blob/master/packages/browser/webpack.common.js)). I'm not familiar with Skypack, is it possible that a similar issue is what prevents bundling ?

**Comment by matthieu-fesselier** [comment] 2021-02-04 13:39
Hi @NSeydoux 

> I think a possible cause for the issue is that node-jose requires some node builtins which must be polyfilled for the bundler to work (see our webpack configuration). I'm not familiar with Skypack, is it possible that a similar issue is what prevents bundling ?

This is a good question, I'm not sure about this. Here is the error I can see from Skypack 
```
 *   Failed to load node_modules/node-forge/lib/baseN.js
 *     'Buffer' is not exported by �node-resolve:empty.js, imported by ../tmp/cdn/_R8Xj3AUn6qFTYvVQkeuh/node_modules/node-forge/lib/baseN.js
 ```

Does it sound familiar?
Actually, it may also be an issue on the `node-forge` side

**Comment by NSeydoux** [comment] 2021-02-04 13:43
It does sound very familiar ^^ : `Buffer` needs to be polyfilled [there](https://github.com/inrupt/solid-client-authn-js/blob/4d40f393b77e01e6d2d600702d8072ab91cf53c7/packages/browser/webpack.common.js#L25) in our Webpack configuration, so I guess something similar is getting in your way.

**Comment by matthieu-fesselier** [comment] 2021-02-04 13:47
Indeed, I did not get it was about the `Buffer` here. I'll dig deeper on the Skypack side to see if this can be fixed and I'll let you know :)

**Comment by matthieu-fesselier** [comment] 2021-06-02 13:13
Hi @NSeydoux ! 

Is the switch to `jose@v3.x` moving forward?  
Currently, we use `solid-client-authn-js` in production, and the library size is around 4MB. Is there any chance it improves with this upgrade?

Thanks!

**Comment by Vinnl** [comment] 2021-06-02 13:38
Hi @matthieu-fesselier, it is in progress though moving slowly because there are [some issues with the upstream library](https://github.com/panva/jose/discussions/201) that we have to deal with. Unfortunately, though [we recently cut some of the size](https://github.com/inrupt/solid-client-authn-js/pull/1411), the main reason for the massive size of the library is the use of a dependency injection library that is preventing tree-shaking. While the jose upgrade should certainly improve things, until we fix that it will unfortunately still be quite a big library.

We _are_ planning to remove that library, but unfortunately that is quite involved and thus won't be done tomorrow.

**Comment by matthieu-fesselier** [comment] 2021-06-02 13:40
Ok got it, thanks for the quick reply!

**Comment by Vinnl** [comment] 2021-06-10 08:15
@matthieu-fesselier It's not released yet, but we just merged the jose upgrade to `main`. While the library is still big, if you compare the [before](https://bundlephobia.com/package/@inrupt/solid-client-authn-browser@1.8.1):

![image](https://user-images.githubusercontent.com/4251/121489620-8e257000-c9d4-11eb-9eb9-d17d7c5effa7.png)

and the [after](https://bundlephobia.com/package/@inrupt/solid-client-authn-browser@1.8.2-feat1608-jose3-915596366-6609-1623084430.0):

![image](https://user-images.githubusercontent.com/4251/121489645-954c7e00-c9d4-11eb-8431-eef1afaa0667.png)

you'll see that it's already quite an improvement :tada:

**Comment by matthieu-fesselier** [comment] 2021-06-10 09:03
Very good news, congrats for the work! Can't wait to see this released :)

**Comment by Vinnl** [comment] 2021-06-16 18:38
1.9.0 was just released and uses the new version of jose. I'm not sure how to run code in Plunker, but when I open the console on your link I don't see an error message.

If you encounter any issues with the new version, please report a new bug. Thanks! :)

**Closed by Vinnl** 2021-06-16 18:38 UTC
Labels: bug

**Comment by matthieu-fesselier** [comment] 2021-06-17 15:04
Seems to work fine indeed, thanks @Vinnl !

**Comment by Vinnl** [comment] 2021-06-18 05:36
Great, thanks for reporting back!
